v1.0.0

diff --git a/vmsm b/vmsm
--- a/vmsm
+++ b/vmsm
@@ -72,6 +72,7 @@ if [ "${userinput}" == "zip"  ]|[ "${userinput2}" == "install"  ]; then
 				echo -e ""
 				echo -e "\033[4;33m Zip installed \033[0m"
 				echo -e "Check zip version with: zip -v"
+				echo -e "Compress a file with: zip -r name.zip file"
 				;;
 		  [nN][oO]|[nN])
 				echo "Quiting"
@@ -85,6 +86,7 @@ if [ "${userinput}" == "zip"  ]|[ "${userinput2}" == "install"  ]; then
 fi
 
 # Install gzip
+
 if [ "${userinput}" == "gzip"  ]|[ "${userinput2}" == "install"  ]; then
 	echo -e ""
 	read -r -p "Do you want to install gzip? [Y/n] " input
@@ -108,6 +110,7 @@ if [ "${userinput}" == "gzip"  ]|[ "${userinput2}" == "install"  ]; then
 fi
 
 # Install curl
+
 if [ "${userinput}" == "curl"  ]|[ "${userinput2}" == "install"  ]; then
 	echo -e ""
 	read -r -p "Do you want to install curl? [Y/n] " input
@@ -129,3 +132,68 @@ if [ "${userinput}" == "curl"  ]|[ "${userinput2}" == "install"  ]; then
 	esac
 	echo -e "================================="
 fi
+
+# Install LinuxGSM
+
+if [ "${userinput}" == "linuxgsm"  ]; then
+	echo -e ""
+	echo -e "Use LinuxGSM here : https://linuxgsm.com/"
+	echo -e "================================="
+fi
+
+# Install NodeJS
+
+if [ "${userinput}" == "nodejs"  ]|[ "${userinput2}" == "install"  ]; then
+	echo -e ""
+	read -r -p "Do you want to install NodeJS? [Y/n] " input
+	 
+	case $input in
+		  [yY][eE][sS]|[yY])
+				sudo apt update && sudo apt install -y nodejs
+				echo -e ""
+				echo -e "\033[4;33m NodeJS installed \033[0m"
+				;;
+		  [nN][oO]|[nN])
+				echo "Quiting"
+				;;
+		  *)
+				echo "Invalid input..."
+				exit 1
+				;;
+	esac
+	echo -e "================================="
+fi
+
+# Add a user to sudoers folder
+
+if [ "${userinput}" == "sudoers"  ]|[ "${userinput2}" == "add"  ]; then
+	echo -e ""
+	echo -e "Enter user name"
+	read user
+	usermod -aG sudo $user
+	echo -e "$user added to sudoers"
+	echo -e "================================="
+fi
+
+# Open a port
+
+if [ "${userinput}" == "port"  ]|[ "${userinput2}" == "open"  ]; then
+	echo -e ""
+	echo -e "Enter port"
+	read port
+	sudo ufw allow $port
+	echo -e "$user port open"
+	echo -e "================================="
+fi
+
+# Close a port
+
+if [ "${userinput}" == "port"  ]|[ "${userinput2}" == "close"  ]; then
+	echo -e ""
+	echo -e "Enter port"
+	read port
+	sudo ufw deny $port
+	echo -e "$user port closed"
+	echo -e "================================="
+fi
+
